#!/usr/bin/python3
import sys

"""
 This is a python script that decodes RSA
"""


def main_func(x):
    # prime_list = [2, 3, 5, 7]
    num = 2
    # res = []

    while num < x:
        if x % num != 0:
            pass
        else:
            print("{:.0f}={:.0f}*{:.0f}".format(x, x/num, num))
            break
        num = num + 1

    # print("haha")


def open_file():

    fin = 0

    if sys.argv[1] is None or len(sys.argv) > 2:
        sys.exit()
    with open(sys.argv[1], 'r') as myfile:
        for line in myfile:
            if line == "" or int(line) < 2:
                sys.exit()
            line = line.split('\n')[0]
            fin = main_func(int(line))
            if fin is None:
                pass
            else:
                print(fin)
    myfile.close()


open_file()
